<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateReportTable extends Migration
{

    public function up()
    {
        //分红表
        Schema::create('report_player_earnings', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->string('prefix',4)->default('A')->commit("用户前端前辍");
            $table->string('rid',255)->nullable();
            $table->bigInteger('top_id')->default(0)->comment("直属ID");                            
            $table->bigInteger('parent_id')->comment("父级ID");                                     
            $table->bigInteger('player_id')->comment("玩家ID"); 
            $table->tinyInteger('is_tester')->default(0)->comment("1,试玩用户，0=正常用户，2=带玩用户");
            $table->bigInteger('inviteplayerid')->default(0)->comment("转介绍代理ID");                      
            $table->string('user_name',64)->comment("帐号");
            $table->integer('level')->comment("用户深度");
            $table->integer('descendantscount')->comment("下级人数");
            $table->integer('registerpersoncount')->comment("新用户注册人数");
            $table->integer('activepersonacount')->comment("活跃人数");
            $table->integer('availableadd')->comment("有效新增");
            $table->bigInteger('self_recharge_amount')->comment("自营充值金额");                                 
            $table->bigInteger('self_withdraw_amount')->comment("自营提现金额");
            $table->bigInteger('team_recharge_amount')->comment("团队充值金额");                                 
            $table->bigInteger('team_withdraw_amount')->comment("团队提现金额");
            $table->bigInteger('directlyunder_recharge_amount')->comment("直属充值金额");                                 
            $table->bigInteger('directlyunder_withdraw_amount')->comment("直属提现金额");
            $table->decimal('casino_winloss',15,4)->default(0.0000)->comment("真人输赢");
            $table->decimal('electronic_winloss',15,4)->default(0.0000)->comment("电子输赢");
            $table->decimal('esport_winloss',15,4)->default(0.0000)->comment("电竞输赢");
            $table->decimal('fish_winloss',15,4)->default(0.0000)->comment("捕鱼输赢");
            $table->decimal('lottery_winloss',15,4)->default(0.0000)->comment("彩票输赢");
            $table->decimal('sport_winloss',15,4)->default(0.0000)->comment("体育输赢");
            $table->decimal('card_winloss',15,4)->default(0.0000)->comment("棋牌输赢");
            $table->bigInteger('casino_gift')->default(0)->comment("真人礼金");                                 
            $table->bigInteger('electronic_gift')->default(0)->comment("电子礼金");
            $table->bigInteger('esport_gift')->default(0)->comment("电竞礼金");                                 
            $table->bigInteger('fish_gift')->default(0)->comment("捕鱼礼金");
            $table->bigInteger('lottery_gift')->default(0)->comment("彩票礼金");                                 
            $table->bigInteger('sport_gift')->default(0)->comment("体育礼金");
            $table->bigInteger('card_gift')->default(0)->comment("棋牌礼金");
            $table->bigInteger('casino_venue_fee')->default(0)->comment("真人场馆费");                                 
            $table->bigInteger('electronic_venue_fee')->default(0)->comment("电子场馆费");
            $table->bigInteger('esport_venue_fee')->default(0)->comment("电竞场馆费");                                 
            $table->bigInteger('fish_venue_fee')->default(0)->comment("捕鱼场馆费");
            $table->bigInteger('lottery_venue_fee')->default(0)->comment("彩票场馆费");                                 
            $table->bigInteger('sport_venue_fee')->default(0)->comment("体育场馆费");
            $table->bigInteger('card_venue_fee')->default(0)->comment("棋牌场馆费");
            $table->bigInteger('casino_commission')->default(0)->comment("真人佣金");                                 
            $table->bigInteger('electronic_commission')->default(0)->comment("电子佣金");
            $table->bigInteger('esport_commission')->default(0)->comment("电竞佣金");                                 
            $table->bigInteger('fish_commission')->default(0)->comment("捕鱼佣金");
            $table->bigInteger('lottery_commission')->default(0)->comment("彩票佣金");                                 
            $table->bigInteger('sport_commission')->default(0)->comment("体育佣金");
            $table->bigInteger('card_commission')->default(0)->comment("棋牌佣金");
            $table->bigInteger('direct_commission')->default(0)->comment("直属贡献分红");                                 
            $table->bigInteger('direct_gift')->default(0)->comment("直属礼金");
            $table->bigInteger('direct_venue_fee')->default(0)->comment("直属场馆费");
            $table->decimal('direct_winloss',15,4)->default(0.0000)->comment("直属游戏输赢");                                 
            $table->bigInteger('team_commission')->default(0)->comment("团队贡献分红");
            $table->bigInteger('team_gift')->default(0)->comment("团队礼金");                                 
            $table->bigInteger('team_venue_fee')->default(0)->comment("团队场馆费");
            $table->decimal('team_winloss',15,4)->default(0.0000)->comment("团队游戏输赢");
            $table->bigInteger('venue_fee')->comment("流水佣金");
            $table->Integer('earnings')->comment("分红比例"); 
            $table->bigInteger('amount')->comment("应发金额");                                     
            $table->bigInteger('real_amount')->comment("实发金额");
            $table->integer('send_day')->default(0)->comment("发放日期");                                      
            $table->integer('from_day')->comment("分红开始日期");                                      
            $table->integer('end_day')->comment("分红结束日期");                                       
            $table->integer('send_time')->default(0)->comment("发放分红时间");                         
            $table->integer('init_time')->comment("生成分红分红时间");                                                                               
            $table->tinyInteger('status')->default(0)->comment("是否发放1=已发放已领取，0=未发放,2=取消发放，3=累积下期，4=已发放未领取");
            $table->bigInteger('lastaccumulation')->default(0)->comment("上次未清");
            $table->bigInteger('accumulation')->default(0)->comment("本月");   
            $table->bigInteger('directlyunder_stock')->comment("直属库存");
            $table->bigInteger('directlyunder_stock_change')->default(0)->comment("直属库存变化");
            $table->bigInteger('team_stock')->comment("团队库存"); 
            $table->bigInteger('team_stock_change')->default(0)->comment("团队库存变化");
            $table->bigInteger('self_stock')->default(0)->comment("自已的库存");
            $table->bigInteger('self_stock_change')->default(0)->comment("自已的库存变化");
            $table->bigInteger('directlyunderDiscountFee')->default(0)->comment("直属彩金费"); 
            $table->bigInteger('directlyunderVenuesFee')->default(0)->comment("直属场馆费");
            $table->bigInteger('teamDiscountFee')->default(0)->comment("团队彩金费");
            $table->bigInteger('teamVenuesFee')->default(0)->comment("团队场馆费");
            $table->Integer('admin_id')->default(0)->comment("管理员ID");
            $table->tinyInteger('type')->default(0)->comment("0=按游戏输赢计算 1=电子捕鱼，2=除电子捕鱼之外的");
            $table->tinyInteger('is_allow_fast_grant')->default(1)->comment("1=允许一键发放");
            $table->bigInteger('tongbao_dividends')->default(0)->comment("通宝模式下级返佣");
            $table->timestamps();

            $table->index("player_id");
            $table->index("user_name");
        });


        //实时分红表
        Schema::create('report_real_player_earnings', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->string('prefix',4)->default('A')->commit("用户前端前辍");
            $table->string('rid',255)->nullable();
            $table->bigInteger('top_id')->default(0)->comment("直属ID");                            
            $table->bigInteger('parent_id')->comment("父级ID");                                     
            $table->bigInteger('player_id')->comment("玩家ID"); 
            $table->tinyInteger('is_tester')->default(0)->comment("1,试玩用户，0=正常用户，2=带玩用户");
            $table->bigInteger('inviteplayerid')->default(0)->comment("转介绍代理ID");                      
            $table->string('user_name',64)->comment("帐号");
            $table->integer('level')->comment("用户深度");
            $table->integer('descendantscount')->comment("下级人数");
            $table->integer('registerpersoncount')->comment("新用户注册人数");
            $table->integer('activepersonacount')->comment("活跃人数");
            $table->integer('availableadd')->comment("有效新增");
            $table->bigInteger('self_recharge_amount')->comment("自营充值金额");                                 
            $table->bigInteger('self_withdraw_amount')->comment("自营提现金额");
            $table->bigInteger('team_recharge_amount')->comment("团队充值金额");                                 
            $table->bigInteger('team_withdraw_amount')->comment("团队提现金额");
            $table->bigInteger('directlyunder_recharge_amount')->comment("直属充值金额"); 
            $table->tinyInteger('directlyunder_recharge_people_number')->default(0)->comment("直属充值人数");  
            $table->integer('register_people_number')->comment("当期注册人数");
            $table->integer('directlyunder_people_number')->comment("所有直属下级");  
            $table->bigInteger('directlyunder_withdraw_amount')->comment("直属提现金额");
            $table->decimal('casino_winloss',15,4)->default(0.0000)->comment("真人输赢");
            $table->decimal('electronic_winloss',15,4)->default(0.0000)->comment("电子输赢");
            $table->decimal('esport_winloss',15,4)->default(0.0000)->comment("电竞输赢");
            $table->decimal('fish_winloss',15,4)->default(0.0000)->comment("捕鱼输赢");
            $table->decimal('lottery_winloss',15,4)->default(0.0000)->comment("彩票输赢");
            $table->decimal('sport_winloss',15,4)->default(0.0000)->comment("体育输赢");
            $table->decimal('card_winloss',15,4)->default(0.0000)->comment("棋牌输赢");
            $table->bigInteger('casino_gift')->default(0)->comment("真人礼金");                                 
            $table->bigInteger('electronic_gift')->default(0)->comment("电子礼金");
            $table->bigInteger('esport_gift')->default(0)->comment("电竞礼金");                                 
            $table->bigInteger('fish_gift')->default(0)->comment("捕鱼礼金");
            $table->bigInteger('lottery_gift')->default(0)->comment("彩票礼金");                                 
            $table->bigInteger('sport_gift')->default(0)->comment("体育礼金");
            $table->bigInteger('card_gift')->default(0)->comment("棋牌礼金");
            $table->bigInteger('casino_venue_fee')->default(0)->comment("真人场馆费");                                 
            $table->bigInteger('electronic_venue_fee')->default(0)->comment("电子场馆费");
            $table->bigInteger('esport_venue_fee')->default(0)->comment("电竞场馆费");                                 
            $table->bigInteger('fish_venue_fee')->default(0)->comment("捕鱼场馆费");
            $table->bigInteger('lottery_venue_fee')->default(0)->comment("彩票场馆费");                                 
            $table->bigInteger('sport_venue_fee')->default(0)->comment("体育场馆费");
            $table->bigInteger('card_venue_fee')->default(0)->comment("棋牌场馆费");
            $table->bigInteger('casino_commission')->default(0)->comment("真人佣金");                                 
            $table->bigInteger('electronic_commission')->default(0)->comment("电子佣金");
            $table->bigInteger('esport_commission')->default(0)->comment("电竞佣金");                                 
            $table->bigInteger('fish_commission')->default(0)->comment("捕鱼佣金");
            $table->bigInteger('lottery_commission')->default(0)->comment("彩票佣金");                                 
            $table->bigInteger('sport_commission')->default(0)->comment("体育佣金");
            $table->bigInteger('card_commission')->default(0)->comment("棋牌佣金");
            $table->bigInteger('direct_commission')->default(0)->comment("直属贡献分红");                                 
            $table->bigInteger('direct_gift')->default(0)->comment("直属礼金");
            $table->bigInteger('direct_venue_fee')->default(0)->comment("直属场馆费");
            $table->decimal('direct_winloss',15,4)->default(0.0000)->comment("直属游戏输赢");                                 
            $table->bigInteger('team_commission')->default(0)->comment("团队贡献分红");
            $table->bigInteger('team_gift')->default(0)->comment("团队礼金");                                 
            $table->bigInteger('team_venue_fee')->default(0)->comment("团队场馆费");
            $table->decimal('team_winloss',15,4)->default(0.0000)->comment("团队游戏输赢");
            $table->bigInteger('venue_fee')->comment("流水佣金");
            $table->Integer('earnings')->comment("分红比例"); 
            $table->bigInteger('amount')->comment("应发金额");                                     
            $table->bigInteger('real_amount')->comment("实发金额");                              
            $table->integer('from_day')->comment("分红开始日期");                                      
            $table->integer('end_day')->comment("分红结束日期");
            $table->integer('day')->default(0)->comment("创建日期");                                          
            $table->bigInteger('lastaccumulation')->default(0)->comment("上次未清"); 
            $table->bigInteger('directlyunder_stock')->comment("直属库存");
            $table->bigInteger('directlyunder_stock_change')->default(0)->comment("直属库存变化");
            $table->bigInteger('team_stock')->comment("团队库存"); 
            $table->bigInteger('team_stock_change')->default(0)->comment("团队库存变化");
            $table->bigInteger('self_stock')->default(0)->comment("自已的库存");
            $table->bigInteger('self_stock_change')->default(0)->comment("自已的库存变化");
            $table->bigInteger('directlyunderDiscountFee')->default(0)->comment("直属彩金费"); 
            $table->bigInteger('directlyunderVenuesFee')->default(0)->comment("直属场馆费");
            $table->bigInteger('teamDiscountFee')->default(0)->comment("团队彩金费");
            $table->bigInteger('teamVenuesFee')->default(0)->comment("团队场馆费");
            $table->tinyInteger('type')->default(0)->comment("0=按游戏输赢计算 1=电子捕鱼，2=除电子捕鱼之外的");
            $table->bigInteger('tongbao_dividends')->default(0)->comment("通宝模式下级返佣");
            $table->timestamps();

            $table->index("player_id");
            $table->index("user_name");
        });


        //流水返佣表
        Schema::create('report_player_commission', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->string('rid',255)->nullable();
            $table->bigInteger('top_id')->default(0)->comment("直属ID");                            
            $table->bigInteger('parent_id')->comment("父级ID");                                     
            $table->bigInteger('player_id')->comment("玩家ID"); 
            $table->tinyInteger('is_tester')->default(0)->comment("1,试玩用户，0=正常用户，2=带玩用户");                      
            $table->string('user_name',64)->comment("帐号");
            $table->integer('level')->comment("用户深度");
            $table->bigInteger('amount')->comment("应发金额");

            $table->bigInteger('team_casino_commission')->comment("团队视讯返佣金额");
            $table->bigInteger('team_electronic_commission')->comment("团队电子返佣金额");
            $table->bigInteger('team_esport_commission')->comment("团队电竞返佣金额");
            $table->bigInteger('team_fish_commission')->comment("团队捕鱼返佣金额");
            $table->bigInteger('team_card_commission')->comment("团队棋牌返佣金额");                                     
            $table->bigInteger('team_sport_commission')->comment("团队体育返佣金额");
            $table->bigInteger('team_lottery_commission')->comment("团队彩票返佣金额");
            $table->bigInteger('directlyunder_casino_commission')->comment("直属视讯返佣金额");
            $table->bigInteger('directlyunder_electronic_commission')->comment("直属电子返佣金额");
            $table->bigInteger('directlyunder_esport_commission')->comment("直属电竞返佣金额");
            $table->bigInteger('directlyunder_fish_commission')->comment("直属捕鱼返佣金额");
            $table->bigInteger('directlyunder_card_commission')->comment("直属棋牌返佣金额");                                     
            $table->bigInteger('directlyunder_sport_commission')->comment("直属体育返佣金额");
            $table->bigInteger('directlyunder_lottery_commission')->comment("直属彩票返佣金额");
            $table->bigInteger('self_casino_commission')->comment("自营视讯返佣金额");
            $table->bigInteger('self_electronic_commission')->comment("自营电子返佣金额");
            $table->bigInteger('self_esport_commission')->comment("自营电竞返佣金额");
            $table->bigInteger('self_fish_commission')->comment("自营捕鱼返佣金额");
            $table->bigInteger('self_card_commission')->comment("自营棋牌返佣金额");                                     
            $table->bigInteger('self_sport_commission')->comment("自营体育返佣金额");
            $table->bigInteger('self_lottery_commission')->comment("自营彩票返佣金额");
            $table->bigInteger('tongbao_commission')->default(0)->comment("通宝模式下级返佣");

            $table->decimal('team_casino_performance',15,4)->default(0.0000)->comment("团队视讯业绩");
            $table->decimal('team_electronic_performance',15,4)->default(0.0000)->comment("团队电子业绩");
            $table->decimal('team_esport_performance',15,4)->default(0.0000)->comment("团队电竞业绩");
            $table->decimal('team_fish_performance',15,4)->default(0.0000)->comment("团队捕鱼业绩");
            $table->decimal('team_card_performance',15,4)->default(0.0000)->comment("团队棋牌业绩");                                     
            $table->decimal('team_sport_performance',15,4)->default(0.0000)->comment("团队体育业绩");
            $table->decimal('team_lottery_performance',15,4)->default(0.0000)->comment("团队彩票业绩");
            $table->decimal('directlyunder_casino_performance',15,4)->default(0.0000)->comment("直属视讯业绩");
            $table->decimal('directlyunder_electronic_performance',15,4)->default(0.0000)->comment("直属电子业绩");
            $table->decimal('directlyunder_esport_performance',15,4)->default(0.0000)->comment("直属电竞业绩");
            $table->decimal('directlyunder_fish_performance',15,4)->default(0.0000)->comment("直属捕鱼业绩");
            $table->decimal('directlyunder_card_performance',15,4)->default(0.0000)->comment("直属棋牌业绩");                                     
            $table->decimal('directlyunder_sport_performance',15,4)->default(0.0000)->comment("直属体育业绩");
            $table->decimal('directlyunder_lottery_performance',15,4)->default(0.0000)->comment("直属彩票业绩");
            $table->decimal('self_casino_performance',15,4)->default(0.0000)->comment("自营视讯业绩");
            $table->decimal('self_electronic_performance',15,4)->default(0.0000)->comment("自营电子业绩");
            $table->decimal('self_esport_performance',15,4)->default(0.0000)->comment("自营电竞业绩");
            $table->decimal('self_fish_performance',15,4)->default(0.0000)->comment("自营捕鱼业绩");
            $table->decimal('self_card_performance',15,4)->default(0.0000)->comment("自营棋牌业绩");                                     
            $table->decimal('self_sport_performance',15,4)->default(0.0000)->comment("自营体育业绩");
            $table->decimal('self_lottery_performance',15,4)->default(0.0000)->comment("自营彩票业绩");

            $table->integer('day')->comment("佣金日期");
            $table->integer('send_time')->default(0)->comment("发放佣金时间");                         
            $table->integer('init_time')->comment("生成佣金时间");                                                                               
            $table->tinyInteger('status')->default(0)->comment("是否发放 0=未发放 ,1=已发放，,2=取消发放");
            $table->string('prefix',4)->default('A')->commit("用户前端前辍"); 
            $table->Integer('admin_id')->default(0)->comment("管理员ID");                         
            $table->timestamps();

            $table->index("player_id");
            $table->index("user_name");
            $table->index("day");
        });

        //实时返佣表
        Schema::create('report_real_player_commission', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->string('rid',255)->nullable();
            $table->bigInteger('top_id')->default(0)->comment("直属ID");                            
            $table->bigInteger('parent_id')->comment("父级ID");                                     
            $table->bigInteger('player_id')->comment("玩家ID"); 
            $table->tinyInteger('is_tester')->default(0)->comment("1,试玩用户，0=正常用户，2=带玩用户");                      
            $table->string('user_name',64)->comment("帐号");
            $table->integer('level')->comment("用户深度");
            $table->bigInteger('amount')->comment("应发金额");

            $table->bigInteger('team_casino_commission')->comment("团队视讯返佣金额");
            $table->bigInteger('team_electronic_commission')->comment("团队电子返佣金额");
            $table->bigInteger('team_esport_commission')->comment("团队电竞返佣金额");
            $table->bigInteger('team_fish_commission')->comment("团队捕鱼返佣金额");
            $table->bigInteger('team_card_commission')->comment("团队棋牌返佣金额");                                     
            $table->bigInteger('team_sport_commission')->comment("团队体育返佣金额");
            $table->bigInteger('team_lottery_commission')->comment("团队彩票返佣金额");
            $table->bigInteger('directlyunder_casino_commission')->comment("直属视讯返佣金额");
            $table->bigInteger('directlyunder_electronic_commission')->comment("直属电子返佣金额");
            $table->bigInteger('directlyunder_esport_commission')->comment("直属电竞返佣金额");
            $table->bigInteger('directlyunder_fish_commission')->comment("直属捕鱼返佣金额");
            $table->bigInteger('directlyunder_card_commission')->comment("直属棋牌返佣金额");                                     
            $table->bigInteger('directlyunder_sport_commission')->comment("直属体育返佣金额");
            $table->bigInteger('directlyunder_lottery_commission')->comment("直属彩票返佣金额");
            $table->bigInteger('self_casino_commission')->comment("自营视讯返佣金额");
            $table->bigInteger('self_electronic_commission')->comment("自营电子返佣金额");
            $table->bigInteger('self_esport_commission')->comment("自营电竞返佣金额");
            $table->bigInteger('self_fish_commission')->comment("自营捕鱼返佣金额");
            $table->bigInteger('self_card_commission')->comment("自营棋牌返佣金额");                                     
            $table->bigInteger('self_sport_commission')->comment("自营体育返佣金额");
            $table->bigInteger('self_lottery_commission')->comment("自营彩票返佣金额");
            $table->bigInteger('tongbao_commission')->default(0)->comment("通宝模式下级返佣");

            $table->decimal('team_casino_performance',15,4)->default(0.0000)->comment("团队视讯业绩");
            $table->decimal('team_electronic_performance',15,4)->default(0.0000)->comment("团队电子业绩");
            $table->decimal('team_esport_performance',15,4)->default(0.0000)->comment("团队电竞业绩");
            $table->decimal('team_fish_performance',15,4)->default(0.0000)->comment("团队捕鱼业绩");
            $table->decimal('team_card_performance',15,4)->default(0.0000)->comment("团队棋牌业绩");                                     
            $table->decimal('team_sport_performance',15,4)->default(0.0000)->comment("团队体育业绩");
            $table->decimal('team_lottery_performance',15,4)->default(0.0000)->comment("团队彩票业绩");
            $table->decimal('directlyunder_casino_performance',15,4)->default(0.0000)->comment("直属视讯业绩");
            $table->decimal('directlyunder_electronic_performance',15,4)->default(0.0000)->comment("直属电子业绩");
            $table->decimal('directlyunder_esport_performance',15,4)->default(0.0000)->comment("直属电竞业绩");
            $table->decimal('directlyunder_fish_performance',15,4)->default(0.0000)->comment("直属捕鱼业绩");
            $table->decimal('directlyunder_card_performance',15,4)->default(0.0000)->comment("直属棋牌业绩");                                     
            $table->decimal('directlyunder_sport_performance',15,4)->default(0.0000)->comment("直属体育业绩");
            $table->decimal('directlyunder_lottery_performance',15,4)->default(0.0000)->comment("直属彩票业绩");
            $table->decimal('self_casino_performance',15,4)->default(0.0000)->comment("自营视讯业绩");
            $table->decimal('self_electronic_performance',15,4)->default(0.0000)->comment("自营电子业绩");
            $table->decimal('self_esport_performance',15,4)->default(0.0000)->comment("自营电竞业绩");
            $table->decimal('self_fish_performance',15,4)->default(0.0000)->comment("自营捕鱼业绩");
            $table->decimal('self_card_performance',15,4)->default(0.0000)->comment("自营棋牌业绩");                                     
            $table->decimal('self_sport_performance',15,4)->default(0.0000)->comment("自营体育业绩");
            $table->decimal('self_lottery_performance',15,4)->default(0.0000)->comment("自营彩票业绩");

            $table->integer('day')->comment("佣金日期");
            $table->string('prefix',4)->default('A')->commit("用户前端前辍");                      
            $table->timestamps();

            $table->index("player_id");
            $table->index("user_name");
            $table->index("day");
        });

        //游戏统计表
        Schema::create('report_gameplat_stat_day', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->integer('main_game_plat_id')->comment("游戏平台");
            $table->integer('personcount')->default(0)->comment("投注人数");
            $table->integer('account')->default(0)->comment("投注次数");
            $table->decimal('available_bet_amount',15,4)->default(0.0000)->comment("有效投注金额"); 
            $table->decimal('company_win_amount',15,4)->default(0.0000)->comment("公司输赢");
            $table->decimal('perperson',15,4)->default(0.0000)->comment("平均投注额");
            $table->decimal('peraccount',15,2)->default(0.00)->comment("人均投注次数");
            $table->text('playerIds')->comment("投注人员id,序列化进去");
            $table->Integer('day')->comment("日期");
            $table->timestamps();

            $table->index(["carrier_id","day"],'c_d');
        });

        //用户日统计
        Schema::create('report_player_stat_day', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->string('rid',255)->nullable();
            $table->bigInteger('top_id')->default(0)->comment("直属ID");                             
            $table->bigInteger('parent_id')->comment("父级ID");                                      
            $table->bigInteger('player_id')->comment("玩家ID");
            $table->string('prefix',4)->default('A')->commit("用户前端前辍");
            $table->tinyInteger('is_tester')->default(0)->comment("1,试玩用户，0=正常用户，2=带玩用户");                      
            $table->string('user_name',64)->comment("帐号");                                     
            $table->integer('level')->comment("层级");                                          
            $table->tinyInteger('type')->comment("1=直属，2=代理，3=会员");                                                                        
            $table->bigInteger('casino_available_bets')->default(0)->comment("自已真人有效投注");
            $table->bigInteger('electronic_available_bets')->default(0)->comment("自已电子有效投注");
            $table->bigInteger('esport_available_bets')->default(0)->comment("自已电竞有效投注");
            $table->bigInteger('fish_available_bets')->default(0)->comment("自已捕鱼有效投注");
            $table->bigInteger('card_available_bets')->default(0)->comment("自已棋牌有效投注");
            $table->bigInteger('sport_available_bets')->default(0)->comment("自已体育有效投注");
            $table->bigInteger('lottery_available_bets')->default(0)->comment("自已彩票有效投注");
            $table->bigInteger('available_bets')->default(0)->comment("自已三方有效投注");
            $table->bigInteger('team_sport_available_bets')->default(0)->comment("团队体育有效投注");
            $table->bigInteger('team_casino_available_bets')->default(0)->comment("团队真人有效投注");
            $table->bigInteger('team_electronic_available_bets')->default(0)->comment("团队电子有效投注");
            $table->bigInteger('team_esport_available_bets')->default(0)->comment("团队电竞有效投注");
            $table->bigInteger('team_fish_available_bets')->default(0)->comment("团队捕鱼有效投注");
            $table->bigInteger('team_card_available_bets')->default(0)->comment("团队棋牌有效投注");
            $table->bigInteger('team_lottery_available_bets')->default(0)->comment("团队彩票有效投注"); 
            $table->bigInteger('team_available_bets')->default(0)->comment("团队三方有效投注"); 
            $table->bigInteger('casino_winorloss')->default(0)->comment("自已真人输赢"); 
            $table->bigInteger('electronic_winorloss')->default(0)->comment("自已电子输赢");
            $table->bigInteger('esport_winorloss')->default(0)->comment("自已电竞输赢");
            $table->bigInteger('fish_winorloss')->default(0)->comment("自已捕鱼输赢");
            $table->bigInteger('card_winorloss')->default(0)->comment("自已棋牌输赢");
            $table->bigInteger('lottery_winorloss')->default(0)->comment("自已彩票输赢");
            $table->bigInteger('sport_winorloss')->default(0)->comment("自已体育输赢");
            $table->bigInteger('win_amount')->default(0)->comment("自已三方输赢"); 
            $table->bigInteger('team_casino_winorloss')->default(0)->comment("团队真人输赢");
            $table->bigInteger('team_electronic_winorloss')->default(0)->comment("团队电子输赢");
            $table->bigInteger('team_esport_winorloss')->default(0)->comment("团队电竞输赢");
            $table->bigInteger('team_fish_winorloss')->default(0)->comment("团队捕鱼输赢");
            $table->bigInteger('team_card_winorloss')->default(0)->comment("团队棋牌输赢");
            $table->bigInteger('team_lottery_winorloss')->default(0)->comment("团队彩票输赢");
            $table->bigInteger('team_sport_winorloss')->default(0)->comment("团队体育输赢");
            $table->bigInteger('team_win_amount')->default(0)->comment("团队三方输赢");
            $table->bigInteger('casino_commission')->default(0)->comment("自已真人返佣"); 
            $table->bigInteger('electronic_commission')->default(0)->comment("自已电子返佣"); 
            $table->bigInteger('esport_commission')->default(0)->comment("自已电竞返佣"); 
            $table->bigInteger('fish_commission')->default(0)->comment("自已捕鱼返佣"); 
            $table->bigInteger('card_commission')->default(0)->comment("自已棋牌返佣");  
            $table->bigInteger('sport_commission')->default(0)->comment("自已体育返佣"); 
            $table->bigInteger('lottery_commission')->default(0)->comment("自已彩票返佣"); 
            $table->bigInteger('commission')->default(0)->comment("自已三方返佣");
            $table->bigInteger('team_casino_commission')->default(0)->comment("团队真人返佣"); 
            $table->bigInteger('team_electronic_commission')->default(0)->comment("团队电子返佣"); 
            $table->bigInteger('team_esport_commission')->default(0)->comment("团队电竞返佣"); 
            $table->bigInteger('team_fish_commission')->default(0)->comment("团队捕鱼返佣"); 
            $table->bigInteger('team_card_commission')->default(0)->comment("团队棋牌返佣");  
            $table->bigInteger('team_sport_commission')->default(0)->comment("团队体育返佣"); 
            $table->bigInteger('team_lottery_commission')->default(0)->comment("团队彩票返佣"); 
            $table->bigInteger('team_commission')->default(0)->comment("团队三方返佣");
            $table->integer('have_bet')->default(0)->comment("自已是否投注");
            $table->integer('team_have_bet')->default(0)->comment("团队投注人数");
            $table->bigInteger('recharge_amount')->default(0)->comment("自已的充值金额");
            $table->bigInteger('team_recharge_amount')->default(0)->comment("团队充值金额");

            $table->bigInteger('agent_recharge_amount')->default(0)->comment("负赢利代理自已的充值金额");
            $table->bigInteger('team_agent_recharge_amount')->default(0)->comment("负赢利代理团队充值金额");

            $table->integer('recharge_count')->default(0)->comment("自已充值次数");
            $table->integer('team_recharge_count')->default(0)->comment("团队充值次数");
            $table->integer('team_recharge_person_number')->default(0)->comment("团队充值人数");
            $table->bigInteger('withdraw_amount')->default(0)->comment("自已提现金额");
            $table->bigInteger('team_withdraw_amount')->default(0)->comment("团队提现金额");
            $table->integer('team_withdraw_person_number')->default(0)->comment("团队提现人数");

            $table->bigInteger('agent_withdraw_amount')->default(0)->comment("负赢利代理自已的提现金额");
            $table->bigInteger('team_agent_withdraw_amount')->default(0)->comment("负赢利代理团队提现金额");
            $table->bigInteger('agent_gift')->default(0)->comment("负赢利代理团队礼金金额");
            $table->bigInteger('team_agent_gift')->default(0)->comment("负赢利代理团队礼金金额");
            $table->bigInteger('put_agent_gift')->default(0)->comment("负赢利代理发给会员礼金金额");
            $table->bigInteger('team_put_agent_gift')->default(0)->comment("负赢利代理团队发给会员礼金金额");

            $table->bigInteger('get_reward')->default(0)->comment("自已收到的打赏金额");
            $table->bigInteger('team_get_reward')->default(0)->comment("团队收到的打赏金额");   
            $table->bigInteger('put_reward')->default(0)->comment("自已发出的打赏金额"); 
            $table->bigInteger('team_put_reward')->default(0)->comment("团队发出的打赏金额");
            $table->bigInteger('gift')->default(0)->comment("自已的彩金金额");
            $table->bigInteger('team_gift')->default(0)->comment("团队彩金金额");
            $table->bigInteger('dividend')->default(0)->comment("自已的分红金额");
            $table->bigInteger('team_dividend')->default(0)->comment("团队分红金额");
            $table->bigInteger('exchange_score')->default(0)->comment("自已积分兑换金额");
            $table->bigInteger('team_exchange_score')->default(0)->comment("自已积分兑换金额");
            $table->integer('first_recharge_count')->default(0)->comment("自已是否首充");
            $table->integer('team_first_recharge_count')->default(0)->comment("团队首充次数");
            $table->bigInteger('first_recharge_amount')->default(0)->comment("自已首充金额");
            $table->bigInteger('team_first_recharge_amount')->default(0)->comment("团队首充金额");
            $table->integer('first_register')->default(0)->comment("自已是否注册");
            $table->integer('team_first_register')->default(0)->comment("团队注册人数");
            $table->bigInteger('stock')->default(0)->comment("直属库存");
            $table->bigInteger('team_stock')->default(0)->comment("团队的库存");
            $table->bigInteger('page_recharge_amount')->default(0)->comment("支付金额");
            $table->bigInteger('page_team_recharge_amount')->default(0)->comment("团队支付金额");
            $table->bigInteger('change_stock')->default(0)->comment("直属库存变化");
            $table->bigInteger('change_team_stock')->default(0)->comment("团队库存变化");
            $table->bigInteger('team_member_first_register')->default(0)->comment("团队支付金额");
            $table->bigInteger('self_stock')->default(0)->comment("自已库存");
            $table->bigInteger('change_self_stock')->default(0)->comment("自已库存变化");

            $table->bigInteger('online_amount')->default(0)->comment("当天最高在线人数");
            $table->tinyInteger('win_lose_agent')->default(0)->comment("负盈利代理，1=是，0=否");                                                                         
            $table->Integer('day')->comment("日期");
            $table->Integer('month')->comment("月份");                                                   
            $table->timestamps();

            $table->index("player_id");
            $table->index("rid");
            $table->index("day");
            $table->index(["player_id","day"]);
            $table->index(["player_id","parent_id"]);
        });

        //月统计表
        Schema::create('report_carrier_month_stat', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('carrier_id')->comment("运营商ID");
            $table->string('prefix',4)->default('A')->commit("用户前端前辍");
            $table->bigInteger('team_available_bets')->default(0)->comment("团队三方有效投注"); 
            $table->bigInteger('team_dividend')->default(0)->comment("团队分红金额");
            $table->integer('team_first_recharge_count')->default(0)->comment("团队首充次数"); 
            $table->integer('team_first_register')->default(0)->comment("团队注册人数");  
            $table->bigInteger('team_gift')->default(0)->comment("团队彩金金额"); 
            $table->integer('team_have_bet')->default(0)->comment("团队投注人数");
            $table->bigInteger('team_lottery_available_bets')->default(0)->comment("团队彩票有效投注"); 
            $table->bigInteger('team_lottery_commission')->default(0)->comment("团队三方返佣"); 
            $table->bigInteger('team_commission')->default(0)->comment("团队彩票返佣");            
            $table->bigInteger('team_lottery_winorloss')->default(0)->comment("团队彩票输赢");
            $table->bigInteger('team_recharge_amount')->default(0)->comment("团队充值金额"); 
            $table->integer('team_recharge_count')->default(0)->comment("团队充值次数");
            $table->bigInteger('team_win_amount')->default(0)->comment("团队三方输赢");
            $table->bigInteger('team_withdraw_amount')->default(0)->comment("团队提现金额");                                                       
            $table->Integer('day_m')->comment("月份");                                                   
            $table->timestamps();

            $table->index(["carrier_id","day_m"]);
        });


    }
    
    public function down()
    {
        Schema::dropIfExists('report_player_earnings');
        Schema::dropIfExists('report_player_stat_day');
        Schema::dropIfExists('report_gameplat_stat_day');
        Schema::dropIfExists('report_carrier_month_stat');
        Schema::dropIfExists('report_player_commission');
        Schema::dropIfExists('report_real_player_commission');
        Schema::dropIfExists('report_real_player_earnings');
    }
}
